### ISSUE TITLE
Crashes on Android with null access

### ISSUE THREAD

**Issue by loonychewy** [CollabPlus/ANE-Can-Open-URL#2]
On Android, when I try to use this ANE, it crashes with the error `[Fault] exception, information=TypeError: Error #1009: Cannot access a property or method of a null object reference.`
This is in CanOpenURL.as, where the extensionContext member is null.
I rebuilt the ANE and it runs fine.
(P.S. Thanks for fixing up the iOS linker option!)

**Comment by gnanaprakash** [comment]
How did you rebuild .ane? using ant build.xml which is part of this project or by some other mean? I have not tested .ane against Android App, so if possible can you share the android test app to test this .ane

**Comment by loonychewy** [comment]
Attached is a test project. Its actually a zip file, so download it and change the extension to .zip

![canopenurltest zip](https://cloud.githubusercontent.com/assets/777139/6074097/5ccc1810-adf2-11e4-9715-08ae5c11f14d.png)

The zip contains a FlashDevelop project.
- The android apk is in the \dist folder. When you run it on device, press cancel when it prompts you for the debugger IP address.
- I've included my working CanOpenUrl.ane and link to it in the attached android apk. So, when you run it, it should say "CanOpenUrl is OK".
- But if you replace the ane with the one from github, then build and run it on Android, you should see an error message

I rebuild the .ane using the ant and the build.xml. But since I'm on Windows, I built the iOS libs on a Mac, then copy it over. I then modify the bulid.xml to skip the Xcode building part and just link in the libCanOpenUrlIosExtension.a.

**Comment by gnanaprakash** [comment]
I'm sorry...I don't able to find the attached .zip file. Can you resend?

**Comment by loonychewy** [comment]
Can you save this URL directly as a .zip instead of a .png?
https://cloud.githubusercontent.com/assets/777139/6074097/5ccc1810-adf2-11e4-9715-08ae5c11f14d.png

**Comment by gnanaprakash** [comment]
Can you download and test the new CanOpenUrl.ane from below dropbox link https://www.dropbox.com/l/c3PbxlzruaFCXxn1HHC7fs 

I have re-complied this particular .ane using java 1.6.x rather than 1.7.x,  it seems there is problem with Adobe platform tools going along with the java 1.7 

http://stackoverflow.com/questions/8977476/adobe-air-3-1-native-extension-for-android-null-extension-context-in-actionscr 
https://forums.adobe.com/message/7119926
http://stackoverflow.com/questions/13594864/how-to-revert-to-java-1-6-on-mac-os-x-10-7-5

**Comment by loonychewy** [comment]
Yes, the new version works!
I wasn't aware of this issue with Java 1.7. There're many versions of JRE on my machine, I don't know which one gets used to compile my ANE. The version in my system default path is Java 1.8.
I'll close this issue then :-)
